#!/usr/bin/env python3
"""
SotaLogger Git Hook 安装脚本
=============================
自动安装 post-commit hook，记录每次 commit 到日志
"""

import os
import sys
import subprocess
from pathlib import Path


def get_project_root() -> Path:
    """获取项目根目录"""
    return Path(__file__).parent.parent


def get_git_root() -> Path:
    """获取 Git 仓库根目录"""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            return Path(result.stdout.strip())
    except Exception:
        pass
    return get_project_root()


def create_post_commit_hook(project_root: Path):
    """创建 post-commit hook"""

    hook_content = '''#!/bin/bash
# ============================================================
# SotaLogger Post-Commit Hook
# Auto-generated by install_hooks.py
# ============================================================

# 获取项目根目录
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# 获取当前 commit 信息
COMMIT_MSG=$(git log -1 --pretty=%B 2>/dev/null | head -1)
FILES_CHANGED=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | tr '\\n' ' ')

# 调用 sota_logger 记录 commit
python3 "$PROJECT_ROOT/tools/sota_logger.py" commit "$COMMIT_MSG" "$FILES_CHANGED" 2>/dev/null

exit 0
'''

    hooks_dir = project_root / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = hooks_dir / "post-commit"

    with open(hook_path, "w", encoding="utf-8") as f:
        f.write(hook_content)

    # 设置执行权限
    os.chmod(hook_path, 0o755)

    return hook_path


def create_post_merge_hook(project_root: Path):
    """创建 post-merge hook (用于 squash merge)"""

    hook_content = '''#!/bin/bash
# ============================================================
# SotaLogger Post-Merge Hook
# Auto-generated by install_hooks.py
# ============================================================

# 检查是否是 squash merge
if [ -z "$GIT_MERGE_AUTOEDIT" ]; then
    exit 0
fi

# 获取项目根目录
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# 获取当前 commit 信息
COMMIT_MSG=$(git log -1 --pretty=%B 2>/dev/null | head -1)
FILES_CHANGED=$(git diff --name-only HEAD~1 HEAD 2>/dev/null | tr '\\n' ' ')

# 调用 sota_logger 记录 merge
python3 "$PROJECT_ROOT/tools/sota_logger.py" commit "$COMMIT_MSG" "$FILES_CHANGED" 2>/dev/null

exit 0
'''

    hooks_dir = project_root / ".git" / "hooks"
    hook_path = hooks_dir / "post-merge"

    with open(hook_path, "w", encoding="utf-8") as f:
        f.write(hook_content)

    os.chmod(hook_path, 0o755)

    return hook_path


def install_hooks():
    """安装所有 SotaLogger hooks"""

    project_root = get_project_root()

    print("""
╔══════════════════════════════════════════════════════════════╗
║              SotaLogger Hook 安装程序                        ║
╚══════════════════════════════════════════════════════════════╝
    """)

    print(f"📂 项目根目录: {project_root}")

    # 创建 post-commit hook
    try:
        hook_path = create_post_commit_hook(project_root)
        print(f"✅ post-commit hook 已安装: {hook_path}")
    except Exception as e:
        print(f"❌ post-commit hook 安装失败: {e}")
        return False

    # 创建 post-merge hook
    try:
        merge_hook_path = create_post_merge_hook(project_root)
        print(f"✅ post-merge hook 已安装: {merge_hook_path}")
    except Exception as e:
        print(f"⚠️ post-merge hook 安装失败 (非致命): {e}")

    print("""
╔══════════════════════════════════════════════════════════════╗
║                    安装完成!                                 ║
╠══════════════════════════════════════════════════════════════╣
║  现在每次 commit 都会自动记录到 sotafollow.log              ║
║                                                              ║
║  查看日志:                                                   ║
║    python3 tools/sota_logger.py view                         ║
║    tail -f sotafollow.log                                   ║
║                                                              ║
║  手动记录:                                                   ║
║    python3 tools/sota_logger.py commit "你的 commit 消息"    ║
║    python3 tools/sota_logger.py report "论文名.md" created   ║
╚══════════════════════════════════════════════════════════════╝
    """)

    return True


def uninstall_hooks():
    """卸载 SotaLogger hooks"""

    project_root = get_project_root()
    hooks_dir = project_root / ".git" / "hooks"

    removed = []

    for hook_name in ["post-commit", "post-merge"]:
        hook_path = hooks_dir / hook_name
        if hook_path.exists():
            # 检查是否是 SotaLogger hook
            try:
                with open(hook_path, "r", encoding="utf-8") as f:
                    content = f.read()
                    if "SotaLogger" in content:
                        hook_path.unlink()
                        removed.append(hook_name)
            except Exception:
                pass

    if removed:
        print(f"✅ 已卸载 hooks: {', '.join(removed)}")
    else:
        print("📭 未找到 SotaLogger hooks")

    return True


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "uninstall":
        uninstall_hooks()
    else:
        install_hooks()
